#ifndef BOMBERMAN_CONST_H
#define BOMBERMAN_CONST_H

enum {
    PLAYER_DOWN,
    PLAYER_WALK_DOWN_1,
    PLAYER_WALK_DOWN_2,
    PLAYER_LEFT,
    PLAYER_WALK_LEFT_1,
    PLAYER_WALK_LEFT_2,
    PLAYER_RIGHT,
    PLAYER_WALK_RIGHT_1,
    PLAYER_WALK_RIGHT_2,
    PLAYER_UP,
    PLAYER_WALK_UP_1,
    PLAYER_WALK_UP_2,
    PLAYER_DIE_1,
    PLAYER_DIE_2,
    PLAYER_DIE_3,
    PLAYER_DIE_4,
    PLAYER_DIE_5,
    PLAYER_DIE_6,
};

enum {
    TILE_WALL,
    TILE_GRASS,
    TILE_SHADOW,
    TILE_BRICK,
    TILE_AIR
};

// Graphics const

#define ZOOM_TEXTURE_ORIGINAL 3
#define SIZE_TEXTURE_TILE_ORIGINAL_PIXEL 16
#define MAP_SIZE_BASE_X 11
#define MAP_SIZE_BASE_Y 13
#define WINDOW_WIDTH 960
//ZOOM_TEXTURE_ORIGINAL * SIZE_TEXTURE_TILE_ORIGINAL_PIXEL * MAP_SIZE_BASE_X
#define WINDOW_HEIGHT 540
//ZOOM_TEXTURE_ORIGINAL * SIZE_TEXTURE_TILE_ORIGINAL_PIXEL * MAP_SIZE_BASE_Y
#define NUMBER_TEXTURE_PER_PLAYER 18
#define TEXTURE_PATH "media/texture/"
#define NUMBER_TILES 5


// Map const

#define FILE_NAME_LIMIT_SIZE 255
#define MAP_PATH "media/map/"
#define LIMIT_SIZE_LINE_MAP_FILE 8192

// Game const

#define NUMBER_MAX_PLAYER 1

#endif
